#1 Enable yt-dlp update during deb package installation
Try to do it automatically during .deb package installation.

diff --git a/packaging/debian/postinst b/packaging/debian/postinst
--- a/packaging/debian/postinst
+++ b/packaging/debian/postinst
@@ -6,7 +6,9 @@ set -e
 
 ## Check if yt-dlp is installed at PATH
 if command -v yt-dlp >/dev/null 2>&1; then
-    printf "\033[32m[INFO] 'yt-dlp' is installed at your system. Mantaine yt-dlp up to date, or consider uninstalling it and get the latest version (for example, you can execute the install_yt-dlp.sh command)...\033[0m\n"
+    printf "\033[32m[INFO] 'yt-dlp' is installed at your system. \033[1m TRYING TO UPDATE yt-dlp...\033[0m\n"
+    yt-dlp -U
+    [ $? -ne 0 ] && printf "\033[33m\033[1m[WARN] CANNOT UPDATE yt-dlp.\033[0m Mantaine yt-dlp up to date, or consider uninstalling it and get the latest version (for example, you can execute the install_yt-dlp.sh command)...\033[0m\n"
 else
     printf "\033[32mTrying to install yt-dlp...\033[0m\n"
     if [ -x /usr/local/bin/install_yt-dlp.sh ]; then
